In [3]:
import numpy as np
import pandas as pd

In [4]:
np.matrix([1,2,3,4],)

matrix([[1, 2, 3, 4]])

In [18]:
vec = [1,2,3,4,5]
n = len(vec)

v = np.matrix([x**i for x in vec for i in range(n)]).reshape(n,n)
v

matrix([[  1,   1,   1,   1,   1],
        [  1,   2,   4,   8,  16],
        [  1,   3,   9,  27,  81],
        [  1,   4,  16,  64, 256],
        [  1,   5,  25, 125, 625]])

1) Write a function so that the columns of the output matrix are powers of the input vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.

In [33]:
def cal_vec(vec,n,increasing  = False):
    n = len(vec)
    
    if increasing:
        v = np.matrix([x**i for x in vec for i in range(n)]).reshape(n,n)
    else:
        v = np.matrix([x**(n-i-1) for x in vec for i in range(n)]).reshape(n,n)
    return v

In [34]:
vec = [3,4,5,6] 
cal_vec(vec,n, True)

matrix([[  1,   3,   9,  27],
        [  1,   4,  16,  64],
        [  1,   5,  25, 125],
        [  1,   6,  36, 216]])

2) Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [39]:
def movingAvrg(input_val, k):
    z = 1
    output = np.convolve(input_val, np.ones(k), 'valid') / k
    for i in output:
        print("y{0} = {1:.2f}".format(z, i))
        z += 1

In [40]:
input_val = np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
k = 3
movingAvrg(input_val, k)

y1 = 5.00
y2 = 4.67
y3 = 5.67
y4 = 6.67
y5 = 9.67
y6 = 28.67
y7 = 49.33
y8 = 72.67
y9 = 84.00
y10 = 93.33
y11 = 116.33
